---
abstract: 'Check your Charles Schwab accounts from Perl'
author:
  - 'Mark Grimes <mgrimes@cpan.org>'
build_requires:
  File::Spec: 0
  Test::More: 0.87
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Finance-Bank-Schwab
provides:
  Finance::Bank::Schwab:
    file: lib/Finance/Bank/Schwab.pm
    version: 1.16
  Finance::Bank::Schwab::Account:
    file: lib/Finance/Bank/Schwab.pm
requires:
  Carp: 0
  Crypt::SSLeay: 0
  WWW::Mechanize: 1
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Finance-Bank-Schwab
  license: http://dev.perl.org/licenses/
  repository: http://github.com/mvgrimes/Finance-Bank-Schwab
version: 1.16
